# Generated by Django 3.1.4 on 2020-12-17 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa_income', models.FloatField(verbose_name='summa_income')),
                ('summa_expenses', models.FloatField(verbose_name='summa_expenses')),
                ('total', models.FloatField(verbose_name='total')),
            ],
        ),
        migrations.CreateModel(
            name='Source_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expenses', 'Expenses')], default='expenses', max_length=100, verbose_name='Type')),
                ('responsible_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Responsible')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField()),
                ('currency', models.CharField(choices=[('dollar', 'Dollar'), ('euro', 'Euro'), ('rub', 'Rub')], default='rub', max_length=100, verbose_name='Currency')),
                ('date_money', models.DateField(verbose_name='date_money')),
                ('date_entry', models.DateTimeField(auto_now_add=True, verbose_name='date_entry')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entry_to_source', to='expenses.source_types', verbose_name='source')),
                ('сategory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entry_to_category', to='expenses.category', verbose_name='category')),
            ],
        ),
    ]
